CREATE TABLE sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    requested_by VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE trace_events (
    trace_id VARCHAR(128) PRIMARY KEY,
    sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    session_id VARCHAR(128) NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    type VARCHAR(64) NOT NULL,
    source VARCHAR(128) NOT NULL,
    summary TEXT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    metadata_json TEXT NOT NULL
);

CREATE INDEX idx_trace_events_session_sequence
    ON trace_events (session_id, sequence_no);
