spring:
  datasource:
    url: ${REPOPILOT_DATABASE_URL}
    username: ${REPOPILOT_DATABASE_USERNAME}
    password: ${REPOPILOT_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
